import type { ResourceDefinition } from "@/types/resource-types";

/**
 * Generates a clean, readable React + Vite project structure
 * configured with AutoAdmin and the provided resources.
 */
export class CodeGenerator {
    /**
     * Generates the content for a standalone 'adminConfig.ts' file
     * which contains the ResourceDefinition array.
     */
    static generateConfigCode(resources: ResourceDefinition[]): string {
        const json = JSON.stringify(resources, (key, value) => {
            if (typeof value === 'function') {
                return `__FUNC__${value.toString()}`;
            }
            return value;
        }, 2);

        // Post-process to remove quotes around functions and identifiers
        const cleaned = json
            .replace(/"__FUNC__(.*?)"/g, '$1')
            .replace(/"([^"]+)":/g, '$1:');

        return `
import { ResourceDefinition } from 'auto-admin';

/**
 * AutoAdmin Resource Configuration
 * This file defines the structure, endpoints, and permissions for your admin panel.
 */
export const adminConfig: ResourceDefinition[] = ${cleaned};
`;
    }

    /**
     * Generates a standard 'App.tsx' entry point.
     */
    static generateAppCode(title: string = "Admin Panel"): string {
        return `
import React from 'react';
import { AdminPanel } from 'auto-admin';
import { adminConfig } from './adminConfig';
import 'auto-admin/dist/index.css';

/**
 * Standard AutoAdmin Entry Point
 */
export default function App() {
  return (
    <div className="h-screen w-full">
      <AdminPanel 
        title="${title}"
        resources={adminConfig}
        defaultDarkMode={true}
      />
    </div>
  );
}
`;
    }

    /**
     * Generates a 'package.json' for the exported project.
     */
    static generatePackageJson(projectName: string = "autoadmin-project"): string {
        return JSON.stringify({
            name: projectName,
            private: true,
            version: "0.1.0",
            type: "module",
            scripts: {
                dev: "vite",
                build: "tsc && vite build",
                preview: "vite preview"
            },
            dependencies: {
                "react": "^19.0.0",
                "react-dom": "^19.0.0",
                "auto-admin": "latest",
                "lucide-react": "latest"
            },
            devDependencies: {
                "@types/react": "^19.0.0",
                "@types/react-dom": "^19.0.0",
                "@vitejs/plugin-react": "^5.0.0",
                "typescript": "^5.7.0",
                "vite": "^6.0.0"
            }
        }, null, 2);
    }

    /**
     * Generates a 'vite.config.ts' file.
     */
    static generateViteConfig(): string {
        return `
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
    }

    /**
     * Generates a simple README.md.
     */
    static generateReadme(projectName: string): string {
        return `
# ${projectName}

This project was generated by **AutoAdmin**.

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`

## Configuration

Edit \`src/adminConfig.ts\` to modify your resource schemas, endpoints, and field mappings.
`;
    }

    /**
     * Generates 'main.tsx' (React 19 style).
     */
    static generateMainTsx(): string {
        return `
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`;
    }

    /**
     * Generates a default 'index.html'.
     */
    static generateIndexHtml(title: string): string {
        return `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
    }
}
