import type { ResourceDefinition } from "@/types/resource-types";

/**
 * Generates a clean, readable React + Vite project structure
 * configured with AutoAdmin and the provided resources.
 */
export class CodeGenerator {
  /**
   * Generates the content for a standalone 'adminConfig.ts' file
   * which contains the ResourceDefinition array.
   */
  static generateConfigCode(resources: ResourceDefinition[]): string {
    const json = JSON.stringify(resources, (_key, value) => {
      if (typeof value === 'function') {
        return `__FUNC__${value.toString()}`;
      }
      return value;
    }, 2);

    // Post-process to remove quotes around functions and identifiers
    const cleaned = json
      .replace(/"__FUNC__(.*?)"/g, '$1')
      .replace(/"([^"]+)":/g, '$1:');

    return `
import { ResourceDefinition } from 'auto-admin';

/**
 * AutoAdmin Resource Configuration
 * This file defines the structure, endpoints, and permissions for your admin panel.
 */
export const adminConfig: ResourceDefinition[] = ${cleaned};
`;
  }

  /**
   * Generates a standard 'App.tsx' entry point.
   */
  static generateAppCode(title: string = "Admin Panel"): string {
    return `
import React from 'react';
import { AdminPanel } from 'auto-admin';
import { adminConfig } from './adminConfig';
import 'auto-admin/dist/index.css';

/**
 * Standard AutoAdmin Entry Point
 */
export default function App() {
  return (
    <div className="h-screen w-full">
      <AdminPanel 
        title="${title}"
        resources={adminConfig}
        defaultDarkMode={true}
      />
    </div>
  );
}
`;
  }

  /**
   * Generates a 'package.json' for the exported project.
   */
  static generatePackageJson(projectName: string = "autoadmin-project"): string {
    return JSON.stringify({
      name: projectName,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview"
      },
      dependencies: {
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "auto-admin": "latest",
        "lucide-react": "latest"
      },
      devDependencies: {
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        "@vitejs/plugin-react": "^5.0.0",
        "typescript": "^5.7.0",
        "vite": "^6.0.0"
      }
    }, null, 2);
  }

  /**
   * Generates a 'vite.config.ts' file.
   */
  static generateViteConfig(): string {
    return `
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
  }

  /**
   * Generates a simple README.md.
   */
  static generateReadme(projectName: string): string {
    return `
# ${projectName}

This project was generated by **AutoAdmin**.

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`

## Configuration

Edit \`src/adminConfig.ts\` to modify your resource schemas, endpoints, and field mappings.
`;
  }

  /**
   * Generates 'main.tsx' (React 19 style).
   */
  static generateMainTsx(): string {
    return `
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`;
  }

  /**
   * Generates a default 'index.html'.
   */
  static generateIndexHtml(title: string): string {
    return `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  }

  /**
   * Generates a 'tsconfig.json' for the exported project.
   */
  static generateTsConfig(): string {
    return JSON.stringify({
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
        noUncheckedSideEffectImports: true,
      },
      include: ["src"],
    }, null, 2);
  }

  /**
   * Generates a single-file API layer that mirrors the AutoAdmin core behavior
   * but is fully decoupled and ready for custom logic.
   */
  static generateApiHooks(resources: ResourceDefinition[]): string {
    const hooks = resources.map((r) => {
      const capitalized = r.name.charAt(0).toUpperCase() + r.name.slice(1);
      const singular = r.name.endsWith('s') ? r.name.slice(0, -1) : r.name;
      const capSingular = singular.charAt(0).toUpperCase() + singular.slice(1);

      return `
// ── ${r.label ?? r.name} Resource Hooks ─────────────────────────────────────

/**
 * Fetch a paginated list of ${r.name}
 */
export function use${capitalized}(params: { page?: number; limit?: number; search?: string } = {}) {
  const { page = 1, limit = 10, search } = params;
  return useQuery({
    queryKey: ['${r.name}', 'list', { page, limit, search }],
    queryFn: async () => {
      const url = new URL('${r.endpoint}', window.location.origin);
      url.searchParams.append('page', String(page));
      url.searchParams.append('limit', String(limit));
      if (search) url.searchParams.append('search', search);
      
      const res = await fetch(url.toString());
      if (!res.ok) throw new Error('Failed to fetch ${r.name}');
      return res.json();
    },
  });
}

/**
 * Fetch a single ${singular} by ID
 */
export function use${capSingular}(id: string | number | undefined) {
  return useQuery({
    queryKey: ['${r.name}', 'detail', id],
    queryFn: async () => {
      if (!id) return null;
      const res = await fetch(\`${r.endpoint}/\${id}\`);
      if (!res.ok) throw new Error('Failed to fetch ${singular}');
      return res.json();
    },
    enabled: !!id,
  });
}

/**
 * CRUD Mutations for ${r.name}
 */
export function use${capitalized}Actions() {
  const queryClient = useQueryClient();
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ['${r.name}'] });
  
  const create = useMutation({
    mutationFn: async (data: Record<string, unknown>) => {
      const res = await fetch('${r.endpoint}', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      if (!res.ok) throw new Error('Failed to create ${singular}');
      return res.json();
    },
    onSuccess: invalidate,
  });

  const update = useMutation({
    mutationFn: async ({ id, data }: { id: string | number; data: Record<string, unknown> }) => {
      const res = await fetch(\`${r.endpoint}/\${id}\`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      if (!res.ok) throw new Error('Failed to update ${singular}');
      return res.json();
    },
    onSuccess: invalidate,
  });

  const remove = useMutation({
    mutationFn: async (id: string | number) => {
      const res = await fetch(\`${r.endpoint}/\${id}\`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete ${singular}');
    },
    onSuccess: invalidate,
  });

  return { create, update, remove };
}`;
    }).join("\n");

    return `
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

/**
 * Auto-generated API hooks for AutoAdmin resources.
 * These hooks provide type-safe data fetching and mutation
 * for your React components.
 */
${hooks}
`;
  }
}
